version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Bangkok 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - WS_TABLE_KEY=${WS_TABLE_KEY}
      - WS_PRINTER_KEY=${WS_PRINTER_KEY}
      - WS_STAFF_KEY=${WS_STAFF_KEY}
      - POS_JWT_SECRET=${POS_JWT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - VITE_APP_API_URL=${VITE_APP_API_URL}
      - VITE_APP_WS_URL=${VITE_APP_WS_URL}
    depends_on:
      - postgres

  frontend:
    build: 
      context: ./react
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_APP_API_URL=${VITE_APP_API_URL}
      - VITE_WS_TABLE_KEY=${VITE_WS_TABLE_KEY}
      - VITE_APP_WS_PRINTER_KEY=${VITE_APP_WS_PRINTER_KEY}
      - VITE_APP_WS_STAFF_KEY=${VITE_APP_WS_STAFF_KEY}
      - VITE_APP_WS_URL=${VITE_APP_WS_URL}
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # ใช้ไฟล์ nginx.conf ที่เตรียมไว้ (วางใน ./nginx/nginx.conf)
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # mount โฟลเดอร์ build ของ React
      - ./react/build:/usr/share/nginx/html:ro
      # mount โฟลเดอร์ใบรับรอง SSL
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app

  postgres:
    image: postgres:15-alpine
    environment:
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
